package com.sovereign.connect.core.temporal.application;

public enum TemporalRequestRejectionCode {
    INVALID_HABITAT_ID,
    INVALID_TEMPORAL_ACT_ID,
    INVALID_DUE_AT,
    INVALID_REQUESTED_AT,
    PAST_DUE_AT_NOT_SUPPORTED,
    MISSING_LABEL,
    MISSING_SIGNAL_KIND,
    MISSING_NOTIFICATION_TARGET_REF,
    MISSING_CREATED_BY_REF,
    MISSING_REQUESTED_BY_REF,
    MISSING_IDEMPOTENCY_KEY,
    IDEMPOTENCY_CONFLICT,
    UNSUPPORTED_PAYLOAD_KIND,
    ACTION_TEMPORAL_PAYLOAD_NOT_SUPPORTED_IN_V1,
    SESSION_IDENTITY_AUTHORITY_POLICY_FIELD_NOT_ALLOWED
}
