package com.sovereign.connect.core.temporal.application;

public enum TemporalRuntimeFailureCode {
    STORAGE_UNAVAILABLE,
    SCHEMA_INCOMPATIBLE,
    SERIALIZATION_FAILURE,
    DESERIALIZATION_FAILURE,
    LEDGER_APPEND_FAILED,
    OUTBOX_APPEND_FAILED,
    IDEMPOTENCY_STORE_UNAVAILABLE,
    TEMPORAL_ENGINE_NOT_READY,
    TEMPORAL_ENGINE_DISABLED,
    RECOVERY_NOT_COMPLETED,
    SINGLE_NODE_GUARD_VIOLATED,
    INTERNAL_FAILURE
}
